/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import bank.TaiKhoan;
import bankclient2.BankClient;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FrmChuyenTien extends javax.swing.JFrame {
    String STK = null;
    BankClient bankClient = new BankClient();
    /**
     * Creates new form FrmChuyenTien
     */
    public FrmChuyenTien(String soTaiKhoan) {
        initComponents();
        STK = soTaiKhoan;
    }

    private FrmChuyenTien() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        a = new javax.swing.JLabel();
        lblSTK = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        txtSTK = new javax.swing.JTextField();
        a2 = new javax.swing.JLabel();
        txtChuyenTien = new javax.swing.JTextField();
        a3 = new javax.swing.JLabel();
        txtGhiCHu = new javax.swing.JTextField();
        btnChuyenTien = new javax.swing.JButton();
        lblHoTen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnMenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnMenu.setText("Trở về");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        a.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a.setText("Từ tài khoản:");

        lblSTK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSTK.setText("123456789");

        a1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a1.setText("Đến số tài khoản:");

        txtSTK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtSTK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSTKKeyPressed(evt);
            }
        });

        a2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a2.setText("Số tiền:");

        txtChuyenTien.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        a3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a3.setText("Nội dung:");

        txtGhiCHu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btnChuyenTien.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnChuyenTien.setText("Thực hiện Chuyển tiền");
        btnChuyenTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenTienActionPerformed(evt);
            }
        });

        lblHoTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHoTen.setText("L");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChuyenTien, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtChuyenTien, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                                .addComponent(a3)
                                .addComponent(lblHoTen)
                                .addComponent(txtGhiCHu))
                            .addComponent(txtSTK, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(a)
                                .addGap(18, 18, 18)
                                .addComponent(lblSTK))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnMenu)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(lblSTK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(a1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSTK, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHoTen)
                .addGap(18, 18, 18)
                .addComponent(a2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChuyenTien, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(a3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGhiCHu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnChuyenTien, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        try {
            FrmMenu f = new FrmMenu(STK);
            f.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    public void Reset() {
        txtSTK.setText("");
        txtChuyenTien.setText("");
        txtGhiCHu.setText("");
    }
    
    private void txtSTKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSTKKeyPressed
        try {
            if(evt.getKeyCode() == 10){
                String stkDen = txtSTK.getText();
                TaiKhoan taikhoanden = bankClient.taiKhoanDen(stkDen);
                if (taikhoanden == null) {
                    lblHoTen.setText("");
                    JOptionPane.showMessageDialog(this, "Số tài khoản không tồn tại");
                } else {
                    lblHoTen.setText(taikhoanden.getHoTen());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtSTKKeyPressed

    private void btnChuyenTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenTienActionPerformed
        try {
            String stkDen = txtSTK.getText();
            String noidung = txtGhiCHu.getText();
            if (txtChuyenTien.getText() != null || txtChuyenTien.getText() != "") {
                long soTienChuyen = Long.parseLong(txtChuyenTien.getText());
                long soTienTu = bankClient.soTien(STK);
                TaiKhoan taikhoanden = bankClient.taiKhoanDen(stkDen);
                if (taikhoanden == null) {
                    JOptionPane.showMessageDialog(this, "Số tài khoản không tồn tại");
                } else if (soTienTu - 50000 < soTienChuyen) {
                    JOptionPane.showMessageDialog(this, "Số tiền chuyển vượt quá số dư tài khoản");
                }else if (soTienChuyen < 0) {
                    JOptionPane.showMessageDialog(this, "Số tiền chuyển phải lớn hơn 0");
                } else if (soTienChuyen > 999999999) {
                    JOptionPane.showMessageDialog(this, "Số tiền chuyển quá lớn");
                } else {
                    int xacnhan = JOptionPane.showConfirmDialog(this,
                        "Đến số tài khoản:" + taikhoanden.getSoTaiKhoan() + "\nHọ tên:" + taikhoanden.getHoTen(),
                        "Xác nhận tài khoản",
                        JOptionPane.YES_NO_OPTION);

                    if (xacnhan == JOptionPane.YES_OPTION) {
                        int result = bankClient.chuyenTien(STK, stkDen, soTienChuyen);
                        if (result > 0) {
                            int rs1 = bankClient.luuChuyenTien(STK, stkDen, -soTienChuyen);
                            int rs2 = bankClient.luuNhanTien(STK, stkDen,  soTienChuyen, noidung);
                            Reset();
                            int xacnhan2 = JOptionPane.showConfirmDialog(this,
                                "Giao dịch thực hiện thành công\nTiếp tục thực hiện giao dịch? ",
                                "Xác nhận giao dịch",
                                    JOptionPane.YES_NO_OPTION);

                            if (xacnhan2 == JOptionPane.YES_OPTION) {
                                FrmMenu f = new FrmMenu(STK);
                                f.setVisible(true);
                                this.dispose();
                            } else {
                                JOptionPane.showMessageDialog(this, "Kết thúc giao dịch");
                                FrmDangNhap f = new FrmDangNhap();
                                f.setVisible(true);
                                this.dispose();
                                STK = null;
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Chuyển tiền thất bại");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Trở lại màn hình");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin");
            }
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập vào số tiền là số!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnChuyenTienActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblHoTen.setText("");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmChuyenTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmChuyenTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmChuyenTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmChuyenTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmChuyenTien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JButton btnChuyenTien;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblSTK;
    private javax.swing.JTextField txtChuyenTien;
    private javax.swing.JTextField txtGhiCHu;
    private javax.swing.JTextField txtSTK;
    // End of variables declaration//GEN-END:variables
}
